---
dist: xenial   # required for Python >= 3.7
language: python
cache: pip
services:
  - docker
python:
  - "3.7"
install:
  - pip install pip -U
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - pip install poetry
  - poetry install -v
  - poetry build -v
script:
  - make test
